[workspace]
authors = ["ken <>"]
channels = ["conda-forge"]
name = "assets"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pillow = ">=11.2.1,<12"
numpy = ">=2.2.5,<3"
